# Generated by Django 5.0.7 on 2025-04-23 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_loginattempt_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroupV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва группи')),
                ('users', models.ManyToManyField(related_name='users_groups_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Група_v2',
                'verbose_name_plural': 'Групи_v2',
                'db_table': 'users_group_v2',
            },
        ),
    ]
