version: '3.9'
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: Tests
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_HOST: db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge