name: Django CI my project

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main



jobs:
  test:
    runs-on: ubuntu-latest  # Контейнер с Ubuntu для запуска job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Проверка кода из репозитория
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Укажите версию Python, нужную для проекта

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Установка зависимостей из requirements.txt

    - name: Set up PostgreSQL
      uses: peter-evans/postgresql-action@v2
      with:
        postgresql_version: '16'  # Укажите версию PostgreSQL
        postgresql_db: 'Tests'  # Имя вашей тестовой базы данных
        postgresql_user: 'test'  # Имя пользователя базы данных
        postgresql_password: 'admin'  # Пароль для базы данных

    - name: Set environment variables
      run: |
        echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
        echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
        echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DEFAULT_SECRET_KEY=${{ secrets.DEFAULT_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_URL=postgres://test:admin@127.0.0.1:5432/Tests" >> $GITHUB_ENV
        echo "DATABASE_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DATABASE_PORT=5432" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test  # Запуск тестов